services:
  redis-service:
    image: "redis:7.0.10-bullseye"
    networks:
      - backend-network
    volumes:
      - "redis-volume:/data"
  web-service:
    build: ./web # Baue Docker-Image für Python/Flask Umgebung
    ports:
      - "80:8000"
    environment:
      REDIS_URL: "redis://redis-service:6379"
    networks:
      - backend-network
    depends_on:
      - redis-service
    command: "gunicorn url_shortener.app:app --bind 0.0.0.0:8000" # Verwende den Gunicorn Webserver aufgrund höherer Stabilität und Skalierbarkeit

networks:
    backend-network:

volumes:
  redis-volume: